---
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: alpha
    image: nginx
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    restartPolicy: Never
    env:
    - name: alpha
  - name: beta
    image: busybox
    command: ['sleep', '4800']
    restartPolicy: Never
    env:
    - name: beta
